### ISSUE TITLE
Desynced Replay

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#915] opened 2016-01-06 11:34 UTC
Hi, here i my desynced replay from todays game:
http://cloud.directupload.net/4Cqn

just wait 10s and download button will appear

**Comment by SoulRaiZor** [comment] 2016-01-06 11:48
here a synced one from MrWeak
http://cloud.directupload.net/4Cqq

**Comment by nixtux** [comment] 2016-01-08 12:26
Pushed a test commit and new version in one, not fully sure if it fixes issue and for now mex finder is disabled, if this does fix issues I can re-enabled mex finder with next engine release

**Comment by SoulRaiZor** [comment] 2016-01-09 06:08
Do we have players who use this widget?
I dont

**Comment by nixtux** [comment] 2016-01-09 06:09
Ok so it not fixed yet, found another reason for desync 

[f=0086207] Fatal: LuaRules: cannot allocate more memory! (805306397 bytes already used, 805306368 bytes maximum)
[f=0086207] Error: LuaRules::RunCallIn: error = 4, GameFrame, [Internal Lua error: Call failure] not enough memory
[f=0086365] Sync error for [BoS]nixtux in frame 86207 (got a02d7ebb, correct is eec46fe9)
[f=0086365] Sync error for [BoS]nixtux in frame 86207 (got a02d7ebb, correct is eec46fe9)
[f=0086615] Sync error for [BoS]nixtux in frame 86608 (got 43d21879, correct is 8d56fcaa)
[f=0086615] Sync error for [BoS]nixtux in frame 86608 (got 43d21879, correct is 8d56fcaa)

**Comment by nixtux** [comment] 2016-01-09 11:50
Its caused by a gadget not widget (LuaRules)

**Comment by nixtux** [comment] 2016-01-13 08:48
Seems fixed now will close issue

**Closed by nixtux** 2016-01-13 08:48 UTC
