### ISSUE TITLE
gaat gun can't morph to viper

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#591] opened 2015-04-05 19:22 UTC
I saw a game where a gaat gun had like 2.8 xp and still couldn't morph to viper, even though requirement is 0.8.

**Comment by nixtux** [comment] 2015-04-06 06:42
Need a replay at least, Closing

**Comment by Bla1** [comment] 2015-04-06 11:51
http://replays.springrts.com/replay/4787215522bd121293874fd03d9f9b82/

Konekat in the south made a gaat gun that couldn't morph despite 2.84 xp

**Comment by nixtux** [comment] 2015-04-06 15:53
how far in ? im not going to watch a 1 hour game

**Comment by Bla1** [comment] 2015-04-06 18:43
Around 20 - 30 minutes I think

**Comment by Bla1** [comment] 2015-04-09 07:00
This is a legit issue... I saw it in another game, so im gonna upload screenshots
![screenshot from 2015-04-09 01 58 22](https://cloud.githubusercontent.com/assets/885667/7061826/1a633798-de5c-11e4-9e35-93f9ee788a47.png)
![screenshot from 2015-04-09 01 58 34](https://cloud.githubusercontent.com/assets/885667/7061827/1bf0411e-de5c-11e4-98be-0002a0c2d378.png)

**Comment by nixtux** [comment] 2015-04-09 17:22
Cant reproduce localy (but have fixed issue with tooltips showing incorrect xp values)
need a short replay with issue

**Comment by Bla1** [comment] 2015-04-10 05:31
Couldn't reproduce locally either, but can produce online. Here is short reply.
http://replays.springrts.com/replay/e55e27556d3cb7ff36ae900bf0eb88b9/
 The thing can only morph to adv gaat around XP 1.0, and viper around XP 3.5

**Closed** 2015-04-10 05:50 UTC
