### ISSUE TITLE
[BUG] Banshee stuck on LLT

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#585] opened 2015-03-17 00:03 UTC
Banshee (Arm t1 Air unit) stuck on light laser tower (LLT).
There are 2 screenshots for your convenience:
http://imgur.com/OO41e9Y,NUxyoHn#0
http://imgur.com/OO41e9Y,NUxyoHn#1

Please address this issue.  Thank you.

**Comment by nixtux** [comment] 2016-07-16 18:27
Cant reproduce in latest engine (102), closing issue

**Closed by nixtux** 2016-07-16 18:27 UTC
